update with logging

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -56,26 +56,33 @@ jobs:
         env:
           RAILS_NEW_GEMFILE: dummy_app_config/gemfiles/Gemfile-rails-${{ matrix.rails-version }}
         run: |
-          bundle config set --local path ".$(mktemp -u -d)"
-          BUNDLE_GEMFILE=$RAILS_NEW_GEMFILE bundle
+          bundle config set --local path "$(mktemp -u -d)"
+          BUNDLE_GEMFILE=$RAILS_NEW_GEMFILE bundle install || exit 1
+
           rails new dummy_app --database=sqlite3 --skip-active-storage --skip-action-cable --skip-spring --skip-listen --skip-test
 
-          # XXX VERY DUMB workaround for Rails 7's "rails new" default Gemfile not working with Ruby 2.7
-          # e.g. https://github.com/abevoelker/devise-passwordless/actions/runs/8132843679/job/22223730812#step:7:292
-          # SUPPOSEDLY Rails 7 supports Ruby 2.7 but the "debug" gem dependency pulls in a "sqlite3" version which is
-          # incompatible with Ruby 2.7
+          # Workaround for Ruby 2.7 with Rails 7
           if [[ "${{ matrix.ruby-version }}" == "2.7" && "${{ matrix.rails-version }}" == "7" ]]; then
             sed -i '/^gem.*sqlite3/d' dummy_app/Gemfile
             echo -e "\ngem 'sqlite3', '~> 1.6.0', '>= 1.6.9'\n" >> dummy_app/Gemfile
           fi
 
+          # Additional logging for debugging
+          echo "Final Gemfile content:"
+          cat dummy_app/Gemfile
+
           cat dummy_app_config/Gemfile.append >> dummy_app/Gemfile
           cd dummy_app
-          bundle install
+
+          # Install dependencies and handle errors
+          bundle install || {
+          echo "Bundle install failed. Exiting.";
+          exit 1;
+          }
           rails g rspec:install
           cp -rf ../dummy_app_config/shared_source/all/* ./
           cp -rf ../dummy_app_config/shared_source/${{ matrix.rails-version }}/* ./
-          yarn install
+          yarn install || exit 1
       - name: Run Rails dummy app tests
         working-directory: ./spec/dummy_app
         run: |
